Shel:
  Neos:
    HealthCheck:
      environments:
#        production:
#          label: 'Production'
#          icon: 'euro-sign'
#          url: ''
#        staging:
#          label: 'Staging'
#          icon: 'flask'
#          url: ''
#          headers:
#            - name: 'Authorization'
#              value: 'Basic <base64-encoded-credentials>'
        development:
          label: 'Development'
          icon: 'user-ninja'
          url: '<current>'
      checks:
        packageVersions:
          include:
            - 'Neos.Neos'
            - 'Neos.Neos.Ui'
        phpConfiguration:
          include:
            - 'memory_limit'
            - 'max_execution_time'
            - 'max_input_time'
            - 'post_max_size'
            - 'upload_max_filesize'
